CREATE USER app WITH PASSWORD 'app';

CREATE DATABASE app;
GRANT ALL PRIVILEGES ON DATABASE app TO app;

\c app

CREATE SCHEMA model;
GRANT ALL PRIVILEGES ON SCHEMA model TO app;
GRANT USAGE ON SCHEMA model TO app;
GRANT ALL ON ALL TABLES IN SCHEMA model TO app;

CREATE DATABASE app_test;
GRANT ALL PRIVILEGES ON DATABASE app_test TO app;

\c app_test

CREATE SCHEMA model;
GRANT ALL PRIVILEGES ON SCHEMA model TO app;
GRANT USAGE ON SCHEMA model TO app;
GRANT ALL ON ALL TABLES IN SCHEMA model TO app;
